"""SQLAlchemy ORM mappings for the schema in `app/db/schema.sql`.

The schema file is the source of truth (per ADR-0007 §"Schema management").
These ORM classes are a hand-written, type-safe view over it. A drift
test in `tests/db/test_schema_init.py` verifies that the set of tables
and columns declared here matches what `schema.sql` produced — so a
column added in one place but forgotten in the other fails at test
time, not at runtime.

Repositories at `app/repositories/*` consume these ORM classes
internally and return frozen Pydantic DTOs to callers. Nothing outside
the repositories should import these ORM classes.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import ForeignKey, Index, LargeBinary, Text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.db.types import UTCEpochSeconds


class Base(DeclarativeBase):
    """Shared declarative base for every ORM mapping."""


class UserORM(Base):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    username: Mapped[str] = mapped_column(Text, unique=True, nullable=False)
    password_hash: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(UTCEpochSeconds, nullable=False)
    last_login_at: Mapped[datetime | None] = mapped_column(UTCEpochSeconds, nullable=True)


class SessionORM(Base):
    __tablename__ = "sessions"

    token_hash: Mapped[bytes] = mapped_column(LargeBinary, primary_key=True)
    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(UTCEpochSeconds, nullable=False)
    expires_at: Mapped[datetime] = mapped_column(UTCEpochSeconds, nullable=False)
    last_seen_at: Mapped[datetime] = mapped_column(UTCEpochSeconds, nullable=False)
    user_agent: Mapped[str | None] = mapped_column(Text, nullable=True)
    ip: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        Index("idx_sessions_user_id", "user_id"),
        Index("idx_sessions_expires_at", "expires_at"),
    )


class ApiTokenORM(Base):
    __tablename__ = "api_tokens"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    token_hash: Mapped[bytes] = mapped_column(LargeBinary, unique=True, nullable=False)
    label: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(UTCEpochSeconds, nullable=False)
    last_used_at: Mapped[datetime | None] = mapped_column(UTCEpochSeconds, nullable=True)
    revoked_at: Mapped[datetime | None] = mapped_column(UTCEpochSeconds, nullable=True)

    __table_args__ = (
        Index("idx_api_tokens_user_id", "user_id"),
        Index("idx_api_tokens_revoked_at", "revoked_at"),
    )


class TargetORM(Base):
    __tablename__ = "targets"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    type: Mapped[str] = mapped_column(Text, nullable=False)
    label: Mapped[str] = mapped_column(Text, nullable=False)
    url: Mapped[str] = mapped_column(Text, nullable=False)
    enabled: Mapped[int] = mapped_column(nullable=False, default=1)
    settings_json: Mapped[str] = mapped_column(Text, nullable=False, default="{}")
    created_at: Mapped[datetime] = mapped_column(UTCEpochSeconds, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(UTCEpochSeconds, nullable=False)

    __table_args__ = (
        Index("idx_targets_type", "type"),
        Index("idx_targets_enabled", "enabled"),
    )


class CredentialORM(Base):
    __tablename__ = "credentials"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    target_id: Mapped[str] = mapped_column(
        Text,
        ForeignKey("targets.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
    )
    lifetime: Mapped[str] = mapped_column(Text, nullable=False)
    ciphertext: Mapped[bytes] = mapped_column(LargeBinary, nullable=False)
    nonce: Mapped[bytes] = mapped_column(LargeBinary, nullable=False)
    salt: Mapped[bytes] = mapped_column(LargeBinary, nullable=False)
    last4: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(UTCEpochSeconds, nullable=False)
    expires_at: Mapped[datetime | None] = mapped_column(UTCEpochSeconds, nullable=True)


class AuditLogORM(Base):
    __tablename__ = "audit_log"

    # SQLite AUTOINCREMENT integer primary key — autogenerated.
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    at: Mapped[datetime] = mapped_column(UTCEpochSeconds, nullable=False)
    event_type: Mapped[str] = mapped_column(Text, nullable=False)
    actor: Mapped[str | None] = mapped_column(Text, nullable=True)
    target_id: Mapped[str | None] = mapped_column(
        Text,
        ForeignKey("targets.id", ondelete="SET NULL"),
        nullable=True,
    )
    data_json: Mapped[str] = mapped_column(Text, nullable=False, default="{}")

    __table_args__ = (
        Index("idx_audit_log_at", "at"),
        Index("idx_audit_log_event_type", "event_type"),
        Index("idx_audit_log_target_id", "target_id"),
    )


class SessionsHistoryORM(Base):
    __tablename__ = "sessions_history"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    started_at: Mapped[datetime] = mapped_column(UTCEpochSeconds, nullable=False)
    ended_at: Mapped[datetime | None] = mapped_column(UTCEpochSeconds, nullable=True)
    end_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    notes_json: Mapped[str] = mapped_column(Text, nullable=False, default="{}")

    __table_args__ = (
        Index("idx_sessions_history_started_at", "started_at"),
        Index("idx_sessions_history_ended_at", "ended_at"),
    )


class SettingsORM(Base):
    __tablename__ = "settings"

    id: Mapped[int] = mapped_column(primary_key=True)
    first_run_complete: Mapped[int] = mapped_column(nullable=False, default=0)
    idle_timeout_seconds: Mapped[int] = mapped_column(nullable=False, default=600)
    log_retention_days: Mapped[int] = mapped_column(nullable=False, default=14)
    ingest_key_current: Mapped[str] = mapped_column(Text, nullable=False)
    ingest_key_previous: Mapped[str | None] = mapped_column(Text, nullable=True)
    ingest_key_rotated_at: Mapped[datetime | None] = mapped_column(UTCEpochSeconds, nullable=True)
    ingest_key_grace_until: Mapped[datetime | None] = mapped_column(UTCEpochSeconds, nullable=True)
    updated_at: Mapped[datetime] = mapped_column(UTCEpochSeconds, nullable=False)


class SystemORM(Base):
    __tablename__ = "system"

    key: Mapped[str] = mapped_column(Text, primary_key=True)
    value_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    value_int: Mapped[int | None] = mapped_column(nullable=True)
    value_blob: Mapped[bytes | None] = mapped_column(LargeBinary, nullable=True)
    updated_at: Mapped[datetime] = mapped_column(UTCEpochSeconds, nullable=False)
