"""First-boot schema bring-up, version check, and crash recovery.

Per ADR-0007:

- Schema lives in `schema.sql` (single source of truth).
- On fresh DB (user_version == 0): execute `schema.sql`, set user_version,
  seed the singleton settings row and the admin user row.
- On a matching version (user_version == SCHEMA_VERSION): no-op.
- On a mismatched version: refuse to start with a clear error pointing
  to the export/reimport procedure (Rule №2: no auto-migration).
- After version reconciliation, scan `sessions_history` for rows with
  `ended_at IS NULL` (control-plane crashed mid-stream) and patch them
  with `end_reason = 'control_plane_crash'`, recording an audit event.

Per ADR-0005 §"Bootstrap" the admin password is resolved before seeding:

- If `RESTREAM_ADMIN_PASSWORD` is set → use that.
- Else → generate a random 20-char URL-safe-base64 passphrase and print
  it to stdout exactly once (the operator captures it from
  ``docker logs``).

The reset flow (`RESTREAM_RESET_ADMIN_PASSWORD=1`) re-hashes the admin
row on subsequent boots and revokes existing sessions implicitly (the
hash change invalidates every prior cookie because session cookies do
not carry the hash, but the rate-limit + per-request session check uses
``last_seen_at`` which the next login refreshes).

Schema bring-up uses the synchronous `sqlite3` driver directly (via
`asyncio.to_thread`) so we can call `executescript` — the canonical
multi-statement entry point that handles comments, string literals,
and trigger bodies. The async engine is used only for the seed,
reset, audit, and crash-recovery paths, which are typed ORM operations.
"""

from __future__ import annotations

import asyncio
import json
import secrets
import sqlite3
import sys
import uuid
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Final, Literal

from pydantic import SecretStr
from sqlalchemy import insert, select, update

from app.crypto import hash_password
from app.db.engine import PRAGMAS
from app.db.models import AuditLogORM, SessionsHistoryORM, SettingsORM, UserORM
from app.logging_setup import get_credential_registry

if TYPE_CHECKING:  # pragma: no cover
    from sqlalchemy.ext.asyncio import AsyncConnection, AsyncEngine

    from app.config import AppSettings


SCHEMA_VERSION: Final[int] = 2
"""Compiled-in schema-shape version. Bump on any change to `schema.sql`.

Per Rule №2 there is no Alembic / migrations chain. A bumped version
causes the boot to refuse to start with a message pointing the
operator at the export → reimport procedure.

Version history:
- 1 (pre-v1.0.0): initial schema with nullable `users.password_hash`.
- 2 (v1.0.0): `users.password_hash NOT NULL` — first-boot password is
  always written by the seed path (env-supplied OR autogenerated per
  ADR-0005 §"Bootstrap"). The NULL state that bricked logins is gone.
"""

ADMIN_USERNAME: Final[str] = "admin"
INGEST_KEY_BYTES: Final[int] = 24  # 32 chars URL-safe base64, ample entropy.

# 15 random bytes → 20 URL-safe-base64 chars (no padding for n%3==0).
# ADR-0005 §"Bootstrap" specifies "20-char passphrase". URL-safe-base64
# alphabet `[A-Za-z0-9_-]` has no shell metacharacters or quote chars,
# so the printed line copy-pastes cleanly into the login form and into
# `RESTREAM_ADMIN_PASSWORD=<value>` on subsequent boots without quoting.
_AUTOGEN_PASSWORD_BYTES: Final[int] = 15
_AUTOGEN_PASSWORD_LENGTH: Final[int] = 20

_SCHEMA_SQL_PATH: Final[Path] = Path(__file__).with_name("schema.sql")

PasswordSource = Literal["env", "autogen", "reset"]


class SchemaVersionMismatchError(RuntimeError):
    """Raised when the on-disk schema version disagrees with the binary.

    Per ADR-0007 the resolution is operator-driven (export + reimport),
    not an in-process migration. The exception message names the
    procedure so the operator sees it in the logs without spelunking.
    """

    def __init__(self, *, on_disk: int, expected: int) -> None:
        self.on_disk = on_disk
        self.expected = expected
        super().__init__(
            f"DB schema version mismatch: on-disk={on_disk}, expected={expected}. "
            f"Restream_Plus does not auto-migrate (ADR-0007, Rule №2). "
            f"To upgrade, export with the old image, start the new image "
            f"against an empty data dir, then reimport. See docs/ops/upgrade.md."
        )


@dataclass(frozen=True, slots=True)
class InitResult:
    """Outcome of `initialize_schema`.

    - `fresh`: True iff this boot created the schema and seed rows.
    - `recovered_session_ids`: IDs of run-sessions that were patched
      from `ended_at IS NULL` → `'control_plane_crash'`.
    - `password_source`: which path wrote the admin hash this boot:
        - "env"     → fresh boot, operator-supplied env var
        - "autogen" → fresh boot, autogenerated + printed to stdout
        - "reset"   → existing DB, `RESTREAM_RESET_ADMIN_PASSWORD=1`
        - None      → existing DB, no rewrite (the normal restart case)
    """

    fresh: bool
    recovered_session_ids: tuple[str, ...]
    password_source: PasswordSource | None


async def initialize_schema(engine: AsyncEngine, settings: AppSettings) -> InitResult:
    """Bring the database up to the expected schema and recover crashes."""
    fresh = await asyncio.to_thread(_sync_bootstrap_schema, settings.db_path)

    password_source: PasswordSource | None = None
    if fresh:
        password, password_source = _resolve_bootstrap_password(settings)
        password_hash = await asyncio.to_thread(hash_password, password.get_secret_value())
        async with engine.begin() as conn:
            await _seed_initial_rows(
                conn,
                password_hash=password_hash,
                source=password_source,
                last4=password.get_secret_value()[-4:],
            )
    elif settings.reset_admin_password and settings.admin_password is not None:
        password_hash = await asyncio.to_thread(
            hash_password, settings.admin_password.get_secret_value()
        )
        async with engine.begin() as conn:
            await _reset_admin_password(
                conn,
                password_hash=password_hash,
                last4=settings.admin_password.get_secret_value()[-4:],
            )
        password_source = "reset"  # noqa: S105 — Literal value, not a credential

    recovered = await _recover_interrupted_sessions(engine)

    return InitResult(
        fresh=fresh,
        recovered_session_ids=recovered,
        password_source=password_source,
    )


def _resolve_bootstrap_password(settings: AppSettings) -> tuple[SecretStr, PasswordSource]:
    """Return the first-boot admin password and how it was sourced.

    Two paths per ADR-0005 §"Bootstrap":

    1. ``RESTREAM_ADMIN_PASSWORD`` set → use it; nothing is printed.
    2. unset → generate 20 URL-safe-base64 chars, print to stdout once,
       register the value with the credential redaction registry so any
       accidental subsequent log mention is scrubbed.

    Side-effects (print + register) happen ONLY in the autogen branch
    and ONLY here. Subsequent calls would re-print — by design this is
    invoked exactly once per process, from inside the ``fresh`` arm of
    ``initialize_schema``.
    """
    if settings.admin_password is not None:
        return settings.admin_password, "env"

    raw = secrets.token_urlsafe(_AUTOGEN_PASSWORD_BYTES)
    # ``token_urlsafe`` for a multiple-of-3 byte count produces no
    # base64 padding, so 15 bytes → 20 chars. Defensive assertion in
    # case the stdlib ever changes this invariant.
    if len(raw) != _AUTOGEN_PASSWORD_LENGTH:  # pragma: no cover - defensive
        raise RuntimeError(
            f"autogen password length {len(raw)} != {_AUTOGEN_PASSWORD_LENGTH}; "
            f"secrets.token_urlsafe contract changed"
        )

    # Print FIRST, then register. If we register before printing, the
    # redaction processor would scrub the value out of any structlog
    # event we happen to emit between register and print. The print
    # path bypasses structlog entirely (raw stdout) precisely so the
    # operator's `docker logs` output contains the literal value on a
    # dedicated stream (structlog renders to stderr per logging_setup).
    _print_autogen_password(raw)
    get_credential_registry().register(raw)

    return SecretStr(raw), "autogen"


def _print_autogen_password(password: str) -> None:
    """Write the autogenerated password to stdout in a sentinel-bracketed block.

    Goes to stdout (not stderr where structlog writes) so that
    structured-log shippers ingesting stderr never see the value. The
    bracketing makes the block visually unmissable in a noisy log stream
    and grep-extractable (``grep -A 6 'FIRST BOOT'`` lifts the whole
    block including the password line).

    ``flush=True`` because s6-overlay buffers stdout per service and a
    crash between the autogen and the next flush would lose the only
    copy of this credential.
    """
    block = (
        "\n"
        "================================================================================\n"
        "RESTREAM_PLUS FIRST BOOT — GENERATED ADMIN PASSWORD\n"
        "Save this password now. It will NOT be shown again.\n"
        "\n"
        f"    Username : {ADMIN_USERNAME}\n"
        f"    Password : {password}\n"
        "\n"
        "Set RESTREAM_ADMIN_PASSWORD on subsequent boots to silence this banner.\n"
        "If lost: restart with RESTREAM_RESET_ADMIN_PASSWORD=1 +\n"
        "RESTREAM_ADMIN_PASSWORD=<new-value>.\n"
        "================================================================================\n"
    )
    sys.stdout.write(block)
    sys.stdout.flush()


def _sync_bootstrap_schema(db_path: Path) -> bool:
    """Synchronously open the DB, apply pragmas, execute schema.sql if fresh.

    Returns True iff this run created the schema (the DB was empty).
    Runs under `asyncio.to_thread` so it doesn't block the event loop.

    Using the sync `sqlite3` driver here lets us call
    `Connection.executescript`, which is the canonical multi-statement
    entry point. The async engine's pragma hook applies the same
    pragmas to its own connections; doing them here too is required so
    `journal_mode = WAL` is set before the schema-creating writes.
    """
    schema_sql = _SCHEMA_SQL_PATH.read_text(encoding="utf-8")
    conn = sqlite3.connect(str(db_path))
    try:
        for key, value in PRAGMAS.items():
            cursor = conn.execute(f"PRAGMA {key} = {value}")
            if key == "journal_mode":
                row = cursor.fetchone()
                actual = (row[0] if row else "").lower()
                if actual != value.lower():
                    raise RuntimeError(
                        f"PRAGMA journal_mode={value!r} did not take effect; "
                        f"SQLite reports journal_mode={actual!r}. "
                        f"Filesystem may not support WAL."
                    )
        on_disk_version = int(conn.execute("PRAGMA user_version").fetchone()[0])
        if on_disk_version == 0:
            conn.executescript(schema_sql)
            conn.execute(f"PRAGMA user_version = {SCHEMA_VERSION}")
            conn.commit()
            return True
        if on_disk_version != SCHEMA_VERSION:
            raise SchemaVersionMismatchError(on_disk=on_disk_version, expected=SCHEMA_VERSION)
        return False
    finally:
        conn.close()


async def _seed_initial_rows(
    conn: AsyncConnection,
    *,
    password_hash: str,
    source: PasswordSource,
    last4: str,
) -> None:
    """Insert the singleton settings row, the admin user row, and an audit row.

    The password hash is always present (the resolver in
    ``_resolve_bootstrap_password`` guarantees a value), so
    ``first_run_complete`` is always set to 1 on a fresh boot. The audit
    row records the password source (``env`` or ``autogen``) for
    forensic review — last4 only, never the plaintext (project invariant).
    """
    now = datetime.now(tz=UTC)

    await conn.execute(
        insert(SettingsORM).values(
            id=1,
            first_run_complete=1,
            idle_timeout_seconds=600,
            log_retention_days=14,
            ingest_key_current=secrets.token_urlsafe(INGEST_KEY_BYTES),
            ingest_key_previous=None,
            ingest_key_rotated_at=None,
            ingest_key_grace_until=None,
            updated_at=now,
        )
    )

    await conn.execute(
        insert(UserORM).values(
            id=uuid.uuid4().hex,
            username=ADMIN_USERNAME,
            password_hash=password_hash,
            created_at=now,
            last_login_at=None,
        )
    )

    event_type = "admin_password_autogenerated" if source == "autogen" else "admin_password_set"
    await conn.execute(
        insert(AuditLogORM).values(
            at=now,
            event_type=event_type,
            actor="system",
            target_id=None,
            data_json=json.dumps(
                {"source": source, "last4": last4},
                separators=(",", ":"),
            ),
        )
    )


async def _reset_admin_password(conn: AsyncConnection, *, password_hash: str, last4: str) -> None:
    """Apply `RESTREAM_RESET_ADMIN_PASSWORD=1` per ADR-0005.

    Re-hashes the admin row and writes an audit entry. Per ADR-0005
    §"Password rotation" the reset path logs to audit; the prior
    implementation omitted this row — closed here as part of the v1.0.0
    bootstrap reconciliation.
    """
    now = datetime.now(tz=UTC)
    await conn.execute(
        update(UserORM)
        .where(UserORM.username == ADMIN_USERNAME)
        .values(password_hash=password_hash)
    )
    # Reset also clears the first-run flag (a reset implies the operator
    # is bringing the system back into a usable state).
    await conn.execute(update(SettingsORM).where(SettingsORM.id == 1).values(first_run_complete=1))
    await conn.execute(
        insert(AuditLogORM).values(
            at=now,
            event_type="admin_password_reset",
            actor="system",
            target_id=None,
            data_json=json.dumps(
                {"source": "reset", "last4": last4},
                separators=(",", ":"),
            ),
        )
    )


async def _recover_interrupted_sessions(engine: AsyncEngine) -> tuple[str, ...]:
    """Patch sessions_history rows with `ended_at IS NULL` per ADR-0007.

    For each orphaned run-session:
    1. Append an `audit_log` row of type `interrupted_session_recovered`
       referencing the prior session id. The audit `data_json` includes
       `started_at` (not an "estimated end" — we have no post-start
       timestamp, so any end-time guess is a lower bound; we record
       the start and let the operator interpret).
    2. UPDATE the row to set `ended_at = started_at` (the lower-bound
       estimate per ADR-0007 — status snapshots are WebSocket-only and
       not persisted) and `end_reason = 'control_plane_crash'`.

    Returns the ids of the patched sessions, in the order patched.
    """
    recovered: list[str] = []
    async with engine.begin() as conn:
        result = await conn.execute(
            select(SessionsHistoryORM.id, SessionsHistoryORM.started_at).where(
                SessionsHistoryORM.ended_at.is_(None)
            )
        )
        rows = result.all()
        now = datetime.now(tz=UTC)
        for row in rows:
            session_id: str = row[0]
            started_at: datetime = row[1]
            await conn.execute(
                insert(AuditLogORM).values(
                    at=now,
                    event_type="interrupted_session_recovered",
                    actor="system",
                    target_id=None,
                    data_json=json.dumps(
                        {
                            "session_id": session_id,
                            "started_at": started_at.isoformat(),
                            "reason": "control_plane_crash",
                            "note": (
                                "ended_at set to started_at; status snapshots "
                                "are WebSocket-only and not persisted, so the "
                                "true end time is unknown"
                            ),
                        },
                        separators=(",", ":"),
                    ),
                )
            )
            await conn.execute(
                update(SessionsHistoryORM)
                .where(SessionsHistoryORM.id == session_id)
                .values(ended_at=started_at, end_reason="control_plane_crash")
            )
            recovered.append(session_id)
    return tuple(recovered)
