"""Schema bring-up, version reconciliation, and crash-recovery tests."""

from __future__ import annotations

import io
import json
from datetime import UTC, datetime
from pathlib import Path
from unittest.mock import patch

import pytest
from app.config import AppSettings
from app.crypto import verify_password
from app.db import (
    SCHEMA_VERSION,
    SchemaVersionMismatchError,
    create_engine,
    initialize_schema,
    make_sessionmaker,
)
from app.db.models import (
    AuditLogORM,
    Base,
    SessionsHistoryORM,
    SettingsORM,
    UserORM,
)
from app.logging_setup import get_credential_registry
from pydantic import SecretStr
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession, async_sessionmaker

from tests.db.conftest import build_settings

# ----------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------


def _captured_autogen_password(stdout: io.StringIO) -> str:
    """Extract the autogen password from the captured stdout block.

    The block format is defined by ``_print_autogen_password`` in
    ``app/db/schema_init.py``. The password line looks like::

        "    Password : <20-char value>"
    """
    for line in stdout.getvalue().splitlines():
        stripped = line.strip()
        if stripped.startswith("Password :"):
            return stripped.split(":", 1)[1].strip()
    raise AssertionError(
        f"no autogenerated password found in stdout; captured:\n{stdout.getvalue()!r}"
    )


@pytest.fixture(autouse=True)
def _reset_credential_registry() -> object:
    """Avoid cross-test contamination of the global redaction registry."""
    get_credential_registry().clear()
    yield
    get_credential_registry().clear()


# ----------------------------------------------------------------------
# Schema bring-up
# ----------------------------------------------------------------------


@pytest.mark.asyncio
async def test_fresh_init_creates_all_tables(engine: AsyncEngine, settings: AppSettings) -> None:
    result = await initialize_schema(engine, settings)
    assert result.fresh is True
    assert result.recovered_session_ids == ()
    # `settings` fixture supplies admin_password → env-set path.
    assert result.password_source == "env"

    expected_tables = {orm.__tablename__ for orm in Base.__subclasses__()}
    # Plus the bookkeeping table SQLite manages for AUTOINCREMENT.
    expected_tables.add("sqlite_sequence")
    async with engine.connect() as conn:
        rows = (
            await conn.exec_driver_sql("SELECT name FROM sqlite_master WHERE type='table'")
        ).all()
    actual_tables = {row[0] for row in rows}
    assert expected_tables.issubset(
        actual_tables
    ), f"missing tables: {expected_tables - actual_tables}"


@pytest.mark.asyncio
async def test_user_version_pragma_is_set(engine: AsyncEngine, settings: AppSettings) -> None:
    await initialize_schema(engine, settings)
    async with engine.connect() as conn:
        result = await conn.exec_driver_sql("PRAGMA user_version")
        assert int(result.scalar_one()) == SCHEMA_VERSION


# ----------------------------------------------------------------------
# Autogen path (env var absent on first boot — ADR-0005 §"Bootstrap")
# ----------------------------------------------------------------------


@pytest.mark.asyncio
async def test_autogen_writes_hash_and_prints_password_block(tmp_path: Path) -> None:
    """Fresh boot with no env var: seed writes a real hash and stdout
    carries the bracketed password block."""
    settings = build_settings(tmp_path)  # admin_password defaults to None
    engine = create_engine(settings)
    stdout_buf = io.StringIO()
    stderr_buf = io.StringIO()
    try:
        with patch("sys.stdout", new=stdout_buf), patch("sys.stderr", new=stderr_buf):
            result = await initialize_schema(engine, settings)
        assert result.fresh is True
        assert result.password_source == "autogen"

        password = _captured_autogen_password(stdout_buf)
        assert len(password) == 20

        sm = make_sessionmaker(engine)
        async with sm() as s:
            user = (await s.execute(select(UserORM))).scalar_one()
            settings_row = (await s.execute(select(SettingsORM))).scalar_one()
        assert user.password_hash is not None
        assert verify_password(user.password_hash, password).ok is True
        assert settings_row.first_run_complete == 1

        # Sentinel + reset hint must be present so the operator does not
        # miss the credential delivery in a noisy log stream.
        out = stdout_buf.getvalue()
        assert "RESTREAM_PLUS FIRST BOOT" in out
        assert "Save this password now" in out
        assert (
            "================================================================================"
            in out
        )
        assert "RESTREAM_RESET_ADMIN_PASSWORD=1" in out

        # The credential block must NOT leak to stderr where structlog
        # routes its JSON output.
        assert password not in stderr_buf.getvalue()
    finally:
        await engine.dispose()


@pytest.mark.asyncio
async def test_autogen_registers_password_with_redaction_registry(tmp_path: Path) -> None:
    """The generated password must be in the registry so any subsequent
    accidental log mention is scrubbed."""
    settings = build_settings(tmp_path)
    engine = create_engine(settings)
    stdout_buf = io.StringIO()
    try:
        with patch("sys.stdout", new=stdout_buf):
            await initialize_schema(engine, settings)
        password = _captured_autogen_password(stdout_buf)
        assert password in get_credential_registry().snapshot()
    finally:
        await engine.dispose()


@pytest.mark.asyncio
async def test_autogen_writes_audit_row_with_last4_only(tmp_path: Path) -> None:
    """Audit row records the autogen event with last4 only — never plaintext."""
    settings = build_settings(tmp_path)
    engine = create_engine(settings)
    stdout_buf = io.StringIO()
    try:
        with patch("sys.stdout", new=stdout_buf):
            await initialize_schema(engine, settings)
        password = _captured_autogen_password(stdout_buf)

        sm = make_sessionmaker(engine)
        async with sm() as s:
            audit_rows = (
                (
                    await s.execute(
                        select(AuditLogORM).where(
                            AuditLogORM.event_type == "admin_password_autogenerated"
                        )
                    )
                )
                .scalars()
                .all()
            )
        assert len(audit_rows) == 1
        data = json.loads(audit_rows[0].data_json)
        assert data == {"source": "autogen", "last4": password[-4:]}
        # Defense in depth: the full password must not appear anywhere in
        # the serialized audit blob.
        assert password not in audit_rows[0].data_json
    finally:
        await engine.dispose()


@pytest.mark.asyncio
async def test_autogen_prints_exactly_once_across_restarts(tmp_path: Path) -> None:
    """Second boot against the same DB is not fresh → no autogen, no print."""
    settings = build_settings(tmp_path)

    engine = create_engine(settings)
    stdout_buf_1 = io.StringIO()
    try:
        with patch("sys.stdout", new=stdout_buf_1):
            first = await initialize_schema(engine, settings)
    finally:
        await engine.dispose()

    engine = create_engine(settings)
    stdout_buf_2 = io.StringIO()
    try:
        with patch("sys.stdout", new=stdout_buf_2):
            second = await initialize_schema(engine, settings)
    finally:
        await engine.dispose()

    assert first.fresh is True
    assert first.password_source == "autogen"
    assert second.fresh is False
    assert second.password_source is None
    assert "RESTREAM_PLUS FIRST BOOT" in stdout_buf_1.getvalue()
    assert "RESTREAM_PLUS FIRST BOOT" not in stdout_buf_2.getvalue()


# ----------------------------------------------------------------------
# Env-supplied password path
# ----------------------------------------------------------------------


@pytest.mark.asyncio
async def test_seed_with_admin_password_writes_hash(tmp_path: Path) -> None:
    settings = build_settings(
        tmp_path,
        admin_password=SecretStr("correct-horse-battery"),
    )
    engine = create_engine(settings)
    stdout_buf = io.StringIO()
    try:
        with patch("sys.stdout", new=stdout_buf):
            result = await initialize_schema(engine, settings)
        assert result.password_source == "env"

        sm = make_sessionmaker(engine)
        async with sm() as s:
            user = (await s.execute(select(UserORM))).scalar_one()
            settings_row = (await s.execute(select(SettingsORM))).scalar_one()
        assert user.password_hash is not None
        verification = verify_password(user.password_hash, "correct-horse-battery")
        assert verification.ok is True
        assert settings_row.first_run_complete == 1

        # No print, no value-leak on the env path.
        assert "RESTREAM_PLUS FIRST BOOT" not in stdout_buf.getvalue()
        assert "correct-horse-battery" not in stdout_buf.getvalue()
    finally:
        await engine.dispose()


@pytest.mark.asyncio
async def test_env_seed_writes_audit_with_source_env_and_last4(tmp_path: Path) -> None:
    settings = build_settings(
        tmp_path,
        admin_password=SecretStr("correct-horse-battery"),
    )
    engine = create_engine(settings)
    try:
        await initialize_schema(engine, settings)
        sm = make_sessionmaker(engine)
        async with sm() as s:
            audit_rows = (
                (
                    await s.execute(
                        select(AuditLogORM).where(AuditLogORM.event_type == "admin_password_set")
                    )
                )
                .scalars()
                .all()
            )
        assert len(audit_rows) == 1
        data = json.loads(audit_rows[0].data_json)
        assert data == {"source": "env", "last4": "tery"}
        assert "correct-horse-battery" not in audit_rows[0].data_json
    finally:
        await engine.dispose()


# ----------------------------------------------------------------------
# Idempotency
# ----------------------------------------------------------------------


@pytest.mark.asyncio
async def test_idempotent_init_on_second_boot(engine: AsyncEngine, settings: AppSettings) -> None:
    first = await initialize_schema(engine, settings)
    second = await initialize_schema(engine, settings)
    assert first.fresh is True
    assert second.fresh is False
    assert second.password_source is None


# ----------------------------------------------------------------------
# Schema-version mismatch
# ----------------------------------------------------------------------


@pytest.mark.asyncio
async def test_version_mismatch_refuses_to_start(tmp_path: Path) -> None:
    settings = build_settings(tmp_path, admin_password="version-mismatch-test-pw")
    engine = create_engine(settings)
    try:
        await initialize_schema(engine, settings)
        # Simulate an older database by clobbering user_version.
        async with engine.begin() as conn:
            await conn.exec_driver_sql("PRAGMA user_version = 999")
        with pytest.raises(SchemaVersionMismatchError) as exc_info:
            await initialize_schema(engine, settings)
        msg = str(exc_info.value)
        # The error must name the export+reimport procedure so an
        # operator reading logs knows what to do.
        assert "export" in msg.lower()
        assert "reimport" in msg.lower() or "import" in msg.lower()
        assert "999" in msg
        assert str(SCHEMA_VERSION) in msg
    finally:
        await engine.dispose()


# ----------------------------------------------------------------------
# Crash recovery
# ----------------------------------------------------------------------


@pytest.mark.asyncio
async def test_crash_recovery_patches_orphan_run_sessions(
    initialized_engine: AsyncEngine,
    settings: AppSettings,
    sessionmaker: async_sessionmaker[AsyncSession],
) -> None:
    """An interrupted run-session (ended_at IS NULL) is closed on next boot."""
    # Inject an orphan row directly — this represents the on-disk state
    # left behind when the control plane crashed mid-stream.
    orphan_id = "run-orphan-1"
    started_at = datetime(2026, 5, 16, 12, 0, 0, tzinfo=UTC)
    async with sessionmaker() as s, s.begin():
        s.add(
            SessionsHistoryORM(
                id=orphan_id,
                started_at=started_at,
                ended_at=None,
                end_reason=None,
                notes_json="{}",
            )
        )

    result = await initialize_schema(initialized_engine, settings)
    assert orphan_id in result.recovered_session_ids

    async with sessionmaker() as s:
        patched = (
            await s.execute(select(SessionsHistoryORM).where(SessionsHistoryORM.id == orphan_id))
        ).scalar_one()
        audit_rows = (
            (
                await s.execute(
                    select(AuditLogORM).where(
                        AuditLogORM.event_type == "interrupted_session_recovered"
                    )
                )
            )
            .scalars()
            .all()
        )

    assert patched.ended_at == started_at
    assert patched.end_reason == "control_plane_crash"
    assert len(audit_rows) == 1
    audit_data = json.loads(audit_rows[0].data_json)
    assert audit_data["session_id"] == orphan_id
    assert audit_data["reason"] == "control_plane_crash"
    # The recovery records `started_at` (not an "estimated_end_at"), because
    # status snapshots are WebSocket-only and not persisted — so any end-time
    # guess is just `started_at`. A `note` field documents this.
    assert audit_data["started_at"] == started_at.isoformat()
    assert "note" in audit_data


# ----------------------------------------------------------------------
# Reset path
# ----------------------------------------------------------------------


@pytest.mark.asyncio
async def test_reset_admin_password_updates_existing_hash(tmp_path: Path) -> None:
    """ADR-0005 reset flow: env vars on subsequent boot rewrite the hash."""
    # Initial boot: no admin password → autogen fires.
    settings_a = build_settings(tmp_path)
    engine = create_engine(settings_a)
    stdout_buf = io.StringIO()
    try:
        with patch("sys.stdout", new=stdout_buf):
            await initialize_schema(engine, settings_a)
    finally:
        await engine.dispose()

    # Subsequent boot with both env vars set.
    settings_b = build_settings(
        tmp_path,
        admin_password=SecretStr("brand-new-password-123"),
        reset_admin_password=True,
    )
    engine = create_engine(settings_b)
    try:
        result = await initialize_schema(engine, settings_b)
        assert result.fresh is False
        assert result.password_source == "reset"

        sm = make_sessionmaker(engine)
        async with sm() as s:
            user = (await s.execute(select(UserORM))).scalar_one()
            settings_row = (await s.execute(select(SettingsORM))).scalar_one()
        assert user.password_hash is not None
        assert verify_password(user.password_hash, "brand-new-password-123").ok is True
        assert settings_row.first_run_complete == 1

        async with sm() as s:
            reset_rows = (
                (
                    await s.execute(
                        select(AuditLogORM).where(AuditLogORM.event_type == "admin_password_reset")
                    )
                )
                .scalars()
                .all()
            )
        assert len(reset_rows) == 1
        data = json.loads(reset_rows[0].data_json)
        assert data == {"source": "reset", "last4": "-123"}
        assert "brand-new-password-123" not in reset_rows[0].data_json
    finally:
        await engine.dispose()


# ----------------------------------------------------------------------
# ORM ↔ schema drift
# ----------------------------------------------------------------------


@pytest.mark.asyncio
async def test_orm_models_match_schema_sql(
    initialized_engine: AsyncEngine,
) -> None:
    """Catch drift: ORM-declared tables vs. tables in the on-disk schema.

    ADR-0007: schema.sql is the source of truth. If a column is added
    to schema.sql but not to models.py (or vice-versa), this test
    fails loudly rather than at INSERT time in some other test.
    """
    orm_tables = {orm.__tablename__ for orm in Base.__subclasses__()}
    async with initialized_engine.connect() as conn:
        rows = (
            await conn.exec_driver_sql("SELECT name FROM sqlite_master WHERE type='table'")
        ).all()
    sql_tables = {row[0] for row in rows} - {"sqlite_sequence"}
    assert orm_tables == sql_tables, (
        f"drift between ORM and schema.sql:\n"
        f"  only-in-ORM: {orm_tables - sql_tables}\n"
        f"  only-in-SQL: {sql_tables - orm_tables}"
    )

    # And every column declared in ORM must exist in schema.sql with
    # the same name (we don't compare types, since SQLAlchemy types
    # render differently — `INTEGER` vs `INT`).
    async with initialized_engine.connect() as conn:
        for orm_cls in Base.__subclasses__():
            table = orm_cls.__tablename__
            decl_columns = {col.name for col in orm_cls.__table__.columns}
            actual_rows = (await conn.exec_driver_sql(f"PRAGMA table_info({table})")).all()
            actual_columns = {row[1] for row in actual_rows}
            assert decl_columns == actual_columns, (
                f"column drift on {table}:\n"
                f"  only-in-ORM: {decl_columns - actual_columns}\n"
                f"  only-in-SQL: {actual_columns - decl_columns}"
            )
